# We would like to keep our Docker image up to date, but we are lazy. How do we do it? We use Github Actions!
name: Docker Image CI

on:
 push:
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - '.dockerignore'
      - 'docker-compose.yml'
      - 'Dockerfile'
    tags:
    - v*
    branches:
    - main
 pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - '.dockerignore'
      - 'docker-compose.yml'
      - 'Dockerfile'
    branches:
    - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # Set-up Docker Buildx Plugin
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Logs into Docker using the credientals from the repository secrets
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # It's about time we pushed the images, eh?
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: brayanbot/brayanbot:latest
