# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        paths-ignore:
            - 'README.md'
            - '.github/**'
            - '.dockerignore'
            - 'docker-compose.yml'
            - 'Dockerfile'
        branches: 
            - main
    pull_request:
        paths-ignore:
            - 'README.md'
            - '.github/**'
            - '.dockerignore'
            - 'docker-compose.yml'
            - 'Dockerfile'
        branches: 
            - main
    schedule:
        - cron: "36 20 * * 6"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install Node v16
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: npm

            - name: Install dependencies
              run: npm ci
    analyze:
        name: Analyze
        runs-on: ubuntu-latest
        permissions:
            actions: read
            contents: read
            security-events: write
        strategy:
            fail-fast: false
            matrix:
                language: ["javascript"]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Initialize CodeQL
              uses: github/codeql-action/init@v1
              with:
                  languages: ${{ matrix.language }}
            - name: Autobuild
              uses: github/codeql-action/autobuild@v1
            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v1
