name: Public Release CI

on:
  push:
    tags: [ "v*" ]
  workflow_dispatch:
  
jobs:
  release-public:
    name: Public Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

        # Set Variables
      - name: Set variables
        id: vars
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/v}

        # Zip up necessary files
      - name: Archive Source code
        run: zip -r BrayanBot-v${{ steps.vars.outputs.version }}.zip * -x Dockerfile docker-compose.yml Dockerignore

        # Download the pterodactyl egg from Zorino's Discord link.
      - name: Receive Pterodactyl Egg
        run: wget -O pterodactyl-egg.json https://cdn.discordapp.com/attachments/940967061566398515/960130923771351110/egg-brayan-bot-v17.json

        # Generate checksums for all files and log them to the appropriate file
      - name: Generate Checksums
        run: |
          FILELIST=
          md5sum BrayanBot-v${{ steps.vars.outputs.version }}.zip pterodactyl-egg.json Dockerfile docker-compose.yml .dockerignore > md5-checksums.txt
          sha256sum BrayanBot-v${{ steps.vars.outputs.version }}.zip pterodactyl-egg.json Dockerfile docker-compose.yml .dockerignore > sha256-checksums.txt
          sha512sum BrayanBot-v${{ steps.vars.outputs.version }}.zip pterodactyl-egg.json Dockerfile docker-compose.yml .dockerignore > sha512-checksums.txt

      # Release Public Build
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "BrayanBot v${{ steps.vars.outputs.version }}"
          files: |
            BrayanBot-*.zip
            pterodactyl-egg.json
            Dockerfile
            docker-compose.yml
            *-checksums.txt
